### ISSUE TITLE
Clamperl

### ISSUE THREAD

**Issue by sirpercival** [Dabomstew/universal-pokemon-randomizer#7] opened 2015-12-06 17:12 UTC
Hi, I used the UPR to fix impossible evolutions and speed up evolutions for Pokemon Black. However, I can't get Clamperl to evolve with either DeepSea item. According to the log, I'm supposed to level it up while holding one, but it doesn't evolve. Any suggestions?

**Comment by Dabomstew** [comment] 2016-02-09 22:12
Closing for now as I'm not able to reproduce it. I tried evolving Clamperl at all 4 times of day (Morning, Day, Evening, Night) with both items on English Pokemon Black and it worked every single time. If this issue persists after the new release which should have better error reporting, feel free to open a new issue.

**Closed by Dabomstew** 2016-02-09 22:12 UTC
